apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: hands-on-ippool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.56.201-192.168.56.210
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: hands-on-l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - hands-on-ippool
